### ISSUE TITLE
feature#2：提供一个 api proxy 测试服务及对应的网站

### ISSUE THREAD

**Issue by freekatz** [MTXAI/api-proxy#2]
免费提供 @1uvu

**Comment by 1uvu** [comment]
测试服务：openai.proxy.mtxai.com，可替代
测试服务主页：https://proxy.mtxai.com

**Comment by 1uvu** [comment]
当前网站和服务 demo 已上线，后面需要引入自动化机制 @1uvu

**Comment by 1uvu** [comment]
提供一个chat网站，类似于 chatgpt 镜像，指定自己的 api key 之后可以直接开始聊天。可以考虑一下支持用户注册登录

**Comment by 1uvu** [comment]
测试服务主页支持切换中英文 @1uvu
